### ISSUE TITLE
本地运行无限“因网络原因掉线, 将于2.00秒后尝试重连”

### ISSUE THREAD

**Issue by gityoud** [LaoLittle/atri_bot#13]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/27655614/213532878-b901bd2d-2f1e-41ac-8fa7-68fe77fe1305.png">
如图所示 我尝试把我的梯子都关掉了 也还是这种情况
途中也保持了大概两三秒连接状态

**Comment by LaoLittle** [comment]
atri login登录使用的协议与atri bot协议不一致，服务器强制断开

**Comment by LaoLittle** [comment]
在[0.8.7](https://github.com/LaoLittle/atri_bot/releases/tag/0.8.7)修复了无限重连的问题，服务器主动断开则不重连
