### ISSUE TITLE
armv7-unknown-linux-musleabihf 插件加载失败

### ISSUE THREAD

**Issue by Miaow233** [LaoLittle/atri_bot#5]
使用 atri_qq-armv7-unknown-linux-musleabihf 无法加载插件，可能是 musl 不支持加载动态库（也可能是不可以跨架构加载？）。
```
2022-09-28 15:25:23  INFO 正在加载插件: libatri_plugin_hi.so
2022-09-28 15:25:23 ERROR 插件(libatri_plugin_hi.so)加载失败: PluginLoadError("无法加载插件动态库: Dynamic loading not supported")
```
我自己打包的 armhf 可以加载。

而且，musl 平台不能编译 dylib。
```
/root/projects/atri_plugin_hi〉cargo build --release --verbose --verbose --jobs 4 --target armv7-unknown-linux-musleabihf
error: cannot produce cdylib for `atri_plugin_hi v0.1.0 (/root/projects/atri_plugin_hi)` as the target `armv7-unknown-linux-musleabihf` does not support these crate types
```

```
/root/atri〉file atri_bot
atri_bot: ELF 32-bit LSB pie executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, BuildID[sha1]=95597a151fa619c31b605c6c56d68648689c8868, for GNU/Linux 3.2.0, stripped
/root/atri〉file atri_qq-armv7-unknown-linux-musleabihf
atri_qq-armv7-unknown-linux-musleabihf: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, stripped
/root/atri〉file plugins/libatri_plugin_hi.so
plugins/libatri_plugin_hi.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=a0cdee72846e103fba32964cb66ae34a87ba104f, with debug_info, not stripped
```

**Comment by LaoLittle** [comment]
尝试过gnu编译加载插件么？

跨架构一般是不能加载插件的，即便是x86和x86_64之间也不行

**Comment by Eumeryx** [comment]
我使用 `RUSTFLAGS="-C target-feature=+crt-static" cargo build` 编译出来的 armv7 musleabihf 插件也无法被相同 target 的 atri_qq 加载，并且这样编译的插件依赖 musl 的 libc.so，不知道是否与此有关。

**Comment by LaoLittle** [comment]
我在x86_64 musl上也得到了相同的结果，估计是musl的问题，但是我记得musl应该是可以使用dlopen的，很奇怪

**Comment by LaoLittle** [comment]
https://github.com/bminor/musl/blob/master/src/ldso/dlopen.c#L6

**Comment by LaoLittle** [comment]
<img width="294" alt="336c0003cde153b0cec795fb94ec2cb5_0" src="https://user-images.githubusercontent.com/93422095/192956715-c02cbaaa-6c14-40ad-b536-895abe028481.png">

<img width="294" alt="97299aa57a2a15d2042c927df8368834_0" src="https://user-images.githubusercontent.com/93422095/192956808-a5be38d5-0b10-421b-960b-40538f84ad18.png">

musl的这个dlopen编译后直接调用了stub_dlopen，所以这是没办法加载的

倒是可以考虑一下使用别的动态链接器，暂时先用gnu把

**Comment by LaoLittle** [comment]
#6
